version: "3"

services:
  node_basic:
    build:
      context: fiserv
    ports:
      - 3000:3000
    working_dir: /usr/src/app

  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./fiserv/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./fiserv/certs/server.crt:/etc/ssl/server.crt
      - ./fiserv/certs/server.key:/etc/ssl/server.key
      - ./fiserv/certs/ca.crt:/etc/nginx/client_certs/ca.crt
